apiVersion: apps/v1
kind: Deployment
metadata:
  name: flaskapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flaskapp
  template:
    metadata:
      labels:
        app: flaskapp
    spec:
      containers:
      - name: flaskapp
        image: rajakhayam/tic-tac-toe-flask:latest
        ports:
        - containerPort: 5000
        imagePullPolicy: Always
